image: maven:3-jdk-8

stages:
    - build
    - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
cache:
  paths:
    - .m2/repository/
    - target/

maven-build-stage:
    stage: build
    script: 
      - mvn clean install
      - mvn package -B
    artifacts:
      paths:
        - target/demo-0.0.1-SNAPSHOT.jar
   
test:
  stage: test
  script: mvn test